### ISSUE TITLE
How to include files from current directory?

### ISSUE THREAD

**Issue by dulguun0225** [dtolnay/automod#2]
I have this file structure. I want to include all files from `src` directory to be included in `lib.rs` as modules
```
src
├───lib.rs
├───mod1.rs
├───mod2.rs
└───mod3.rs
```
I tried these but didn't work. 
```rust
// lib.rs
automod::dir!(".");
automod::dir!("./");
```
How do I include files from current directory as modules?

**Comment by dtolnay** [comment]
The dir path is relative to the directory containing Cargo.toml, so for that setup it would be `automod::dir!("src")`.

Make sure to use automod 0.2 so that you pull in #3.

**Comment by dulguun0225** [comment]
I thought it was relative to the path it's used. Thanks now it works.

**Comment by dulguun0225** [comment]
Using it causes some other code to break. 

It says `recursion limit reached while expanding the macro $crate::format_args`. 
```rust
        write!(
            f,
            "{}: {:.3}°{} {:.3}°{}",
            self.name,
            self.lat.abs(),
            lat_c,
            self.lon.abs(),
            lon_c
        )
```

Any idea why?

**Comment by dtolnay** [comment]
Can you make a minimal repro so I can reproduce what you are seeing?

**Comment by dulguun0225** [comment]
Error is in the `hello_fmt.rs`. When I comment out `automod::dir!("src");` in the `lib.rs` and uncomment other lines the error disappears.
[https://github.com/dulguun0225/rust_by_example](https://github.com/dulguun0225/rust_by_example)

**Comment by dtolnay** [comment]
It looks like you are not using 0.2. https://github.com/dtolnay/automod/issues/2#issuecomment-576504470

You need to change https://github.com/dulguun0225/rust_by_example/blob/d96e5da5662d464e14279e1fb1cb2d56cd5cbfe2/Cargo.toml#L10 to say `automod = "0.2"`.

**Comment by dulguun0225** [comment]
Thanks now it works. I thought `*` meant latest version.

**Comment by dtolnay** [comment]
`*` means any version, but your code doesn't work with any version, only with 0.2. Glad it works now!
