### ISSUE TITLE
Use path attribute for modules with hyphen in filename

### ISSUE THREAD

**Issue by Luro02** [dtolnay/automod#4]
My folder structure is the following

```
tests/
├── issues
│   ├── issue-00055.rs
│   └── mod.rs
├── master_playlist.rs
├── media_playlist.rs
├── mod.rs
├── rfc8216.rs
└── version-number.rs
```

`tests/issues/mod.rs` contains

```rust
automod::dir!("tests/issues");
```

and the `proc-macro` panics with

```
error: proc macro panicked
 --> tests/issues/mod.rs:3:1
  |
3 | automod::dir!("tests/issues");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: `"issue-00055"` is not a valid identifier
```

---

This issue can be solved by generating the following for the above example

```rust
#[path = "tests/issues/issue-00055"]
mod issue_00055;
```

https://stackoverflow.com/a/57535534/7766117

### Why would I want to do this?

As the stackoverflow answer mentions

> However this is not common, and I wouldn't recommand it. Just stick with snake_case for module names.

this should normally not be done, but I prefer to have my files separated by hyphens in this case, because it looks better and the rust repository does the same:
https://github.com/rust-lang/rust/tree/master/src/test/ui/issues

**Comment by dtolnay** [comment]
I would accept a PR to fix this.
