### ISSUE TITLE
can make mod pub?

### ISSUE THREAD

**Issue by jesse996** [dtolnay/automod#6]
I want something like `pub automod::dir!("path/to/directory");`,
can that possible?

**Comment by dtolnay** [comment]
I published 0.2.2 with support for a visibility. `automod::dir!(pub "path/to/directory");`

**Comment by jesse996** [comment]
> I published 0.2.2 with support for a visibility. `automod::dir!(pub "path/to/directory");`

thank you ，that's cool~
